### ISSUE TITLE
Bluetooth wireless keyboard

### ISSUE THREAD

**Issue by bil-ash** [mircerlancerous/cordova-plugin-keyboard#2]
Can this plugin be used in conjunction with a bluetooth plugin so that one phone acts as an external keyboard and the other as the device on which keystrokes are entered?

**Comment by mircerlancerous** [comment]
This plugin is designed to intercept/record keyboard events from a hardware keyboard plugged into an android device. If that is your use-case, then yes this could be used as you describe. It sounds like though your application would be better suited to use a virtual keyboard. It could be that this can also detect virtual key events but there are better ways of doing this that don't require a plugin (ie onchange, or input polling).
